### ISSUE TITLE
After update failed to load leagues

### ISSUE THREAD

**Issue by TrueEdge** [SnosMe/awakened-poe-trade#1523]
After the update I get the message failed to load leagues. When I click on show in Browser I get the leagues listed (in json??) Tried restarting the program.

https://www.screenpresso.com/=iqSsSiM2Bn0O

**Comment by liuloic** [comment]
I got the same error

![Image](https://github.com/user-attachments/assets/a48c2dfb-f450-4d91-bd0e-947ca21abf1d)

![Image](https://github.com/user-attachments/assets/4a9b2509-7890-42c4-80f1-2ee0ab4fbbe0)

**Comment by premoe** [comment]
also getting the same exact error

**Comment by rntsza** [comment]
Same here

**Comment by Xebtria** [comment]
same here
https://i.vgy.me/oHLl1N.png

then on clicking on browser, getting the same json.

settings in game:
https://i.vgy.me/a6VZcT.png

settings in browser:
https://i.vgy.me/GRs2Qx.png

**Comment by lilpaniniuwu** [comment]
same going back to the previous version fixed it for now

**Comment by Xebtria** [comment]
> same going back to the previous version fixed it for now

with idols not working, which was the point of the update. that being said, better something where idols are not working than something where nothing is working

**Comment by premoe** [comment]
I got it to work by deleting every single old file and then running the installer again

**Comment by TrueEdge** [comment]
> I got it to work by deleting every single old file and then running the installer again. I had one folder with the old 3.23 files that didnt get removed when running the uninstaller so deleted them manually and now it seems to work.

That didnt work for me. Guess I go back one version till bug is fixed

**Comment by DavidBindloss** [comment]
Can I necro this? I'm still getting this error on 3.25.104 - exactly the same set of symptoms.
