### ISSUE TITLE
Getting ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Razunter** [SnosMe/awakened-poe-trade#1555]
![Image](https://github.com/user-attachments/assets/d9aef720-abaa-45b9-ba1d-0e2f2b2f1f98)

Error pops up constantly.
Probably related to my country's censorship, but it shouldn't block usage of the app.

**Comment by lLooneyl** [comment]
The same problem when starting the software
[17:03:06] info Windows_NT 10.0.26100 / v3.26.101
[17:03:15] error [cors-proxy] net::ERR_QUIC_PROTOCOL_ERROR (poe.ninja)

![Image](https://github.com/user-attachments/assets/1a0bb1ab-3524-4fd9-a802-0a526efa2345)

Is there a solution? The error appears regularly on top of games
Well, I'm sure it's related or not, but when I tried to minimize game, the PC stopped accepting mouse input LMB

**Comment by SnosMe** [comment]
There is already error handling code there https://github.com/SnosMe/awakened-poe-trade/blob/af541abe2059cd6dd6560bac34f97af890dcd211/main/src/proxy.ts#L49

And I have no idea how to reproduce your issue.

**Comment by lLooneyl** [comment]
> And I have no idea how to reproduce your issue.

Appears when I launch Awakened Poe Trade
And not at regular intervals in the game =/
I don't know how to provide you with additional logs

**Comment by SnosMe** [comment]
Try `--disable-quic` flag, but I'm not sure if Electron passes it to Chromium.

**Comment by lLooneyl** [comment]
> Try `--disable-quic` flag, but I'm not sure if Electron passes it to Chromium.

I don't understand where this needs to be written?

**Comment by SnosMe** [comment]
Don't forget to quit first.

![Image](https://github.com/user-attachments/assets/3a057d76-1668-4fc5-967b-7720e82bb1e4)

**Comment by lLooneyl** [comment]
I noticed an interesting issue while playing.
An error popped up — I closed it and tried to reproduce the situation.  
Here’s the logic:  
Checked the price on an item, closed the window, and 2–3 seconds later the error appeared.
I repeated the steps and tried to open the APT settings with Shift + Space.  
My PC stopped responding to almost all mouse and keyboard actions.  
It felt like an invisible APT window was triggered and blocked everything except the Windows downbar.
I managed to unlock the system only by force-closing the game through the Windows downbar.

**Comment by lLooneyl** [comment]
> Don't forget to quit first.
> 
> ![Image](https://github.com/user-attachments/assets/3a057d76-1668-4fc5-967b-7720e82bb1e4)

I'll do it now. The error did not appear when I launched Awakened Poe Trade APT! I am watching further

**Comment by Styml** [comment]
Had the same issue, the fix works.

**Comment by Hovl111** [comment]
> Don't forget to quit first.
> 
> ![Image](https://github.com/user-attachments/assets/3a057d76-1668-4fc5-967b-7720e82bb1e4)

That worked for me, had same issue, thanks

**Comment by Roman-Karman** [comment]
Have the same issue, the fix works
But in debug have this:
`[11:34:29] error [cors-proxy] net::ERR_QUIC_PROTOCOL_ERROR (poe.ninja)`
There was no such problem on the awp 3.25* version, I checked yesterday. I can't say the exact version because I've already updated.
I admit that my location also plays a role - Russia, our resources (sites, etc.) that are behind cloudflare work poorly here
But, I repeat, there was no such problem on the previous version.

![Image](https://github.com/user-attachments/assets/b6baee74-b58a-4141-a27b-3b1d734fa4c4)

**Comment by Razunter** [comment]
@Roman-Karman it's not about the version, it's just poe.ninja is blocked in Russia now.

**Comment by ecoconceptcars** [comment]
> [@Roman-Karman](https://github.com/Roman-Karman) it's not about the version, it's just poe.ninja is blocked in Russia now.

It's not true. I'm in Russia and poe.ninja works here without vpn or any things. And I have the same error lLooneyl wrote about.

**Comment by Roman-Karman** [comment]
Today the incorrect work of resources stopped and everything works correctly. I launched it without the flag and I don't encounter any errors.

**Comment by AiSatan** [comment]
same issue, Asia.

**Comment by aggnplz** [comment]
<img width="570" height="134" alt="Image" src="https://github.com/user-attachments/assets/06afcf52-d273-491f-a0ad-a2c9aca19a89" />

After today's update, the issue persisted. Any ideas? doing --disable-quic or --disable-http2 doesn't seem to fix the issue.

**Comment by aggnplz** [comment]
> <img alt="Image" width="570" height="134" src="https://private-user-images.githubusercontent.com/75488569/512871457-06afcf52-d273-491f-a0ad-a2c9aca19a89.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI4ODY2NjgsIm5iZiI6MTc2Mjg4NjM2OCwicGF0aCI6Ii83NTQ4ODU2OS81MTI4NzE0NTctMDZhZmNmNTItZDI3My00OTFmLWEwYWQtYTJjOWFjYTE5YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTExVDE4MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmU1ODY0NzVmM2E4NmFjZDk3Y2M3MDBmZjA2ZTkzMmIwNjJjZTU1Nzc0ODZiOGFkNGE5NGVlMzBlYzhjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zWIWgHQmbwGMPDqfKgwar0muVy8VGBNETP_72MWocUo">
> 
> After today's update, the issue persisted. Any ideas? doing --disable-quic or --disable-http2 doesn't seem to fix the issue.

And now this

<img width="561" height="209" alt="Image" src="https://github.com/user-attachments/assets/63c2f6b2-f318-428f-a1dc-cbac82e32777" />

**Comment by SnosMe** [comment]
can you open poe.ninja in regular browser?

**Comment by aggnplz** [comment]
> can you open poe.ninja in regular browser?

can open poe.ninja fine

<img width="1323" height="722" alt="Image" src="https://github.com/user-attachments/assets/c1186941-a68a-4023-9690-923bd5f9d04f" />

**Comment by psidbo-web** [comment]
I've been having this issue over the last few days, the --disable-quic and/or --disable-http2 didn't seem to make a difference. What does appear to have worked for me though, is to change DNS provider away from Cloudflare (so removing 1.1.1.1 and 1.0.0.1) to use Google's 8.8.8.8 and Quad9 9.9.9.9. QUIC is a google/chrome thing so maybe something new/updated is getting in the way with the ap lookups.

**Comment by Ralwythgar** [comment]
**Description**  
The same problem persists; the suggested fix does not resolve it.  
There is no error handling, and the popup steals focus, making mapping with APT impossible.

**Error Log**  (lots of the same)
[5:47:28 PM] error [cors-proxy] net::ERR_HTTP2_PROTOCOL_ERROR (poe.ninja)

**Additional Info / Questions**  
Can the tool be configured to stop polling `poe.ninja` every 2 minutes?

**Comment by aggnplz** [comment]
> can you open poe.ninja in regular browser?

Hi, just want to drop in and show my gratitude. Issues are now fixed. Bless your RNG.

**Comment by regulyarniy** [comment]
Issue still persist one year later. 
`--disable-quic` not helping a lot
I had same issues in 3.28 and 3.29 leagues when checking prices every 5-10 try, very annoying. It may be reproducing because im in Russian and national firewall is blocking something.
Please do something with it, why UI is blocked with exception? Could you just catch\ignore it silently?
<img width="686" height="249" alt="Image" src="https://github.com/user-attachments/assets/ee52ead2-0d2e-4715-aba4-3e952860203c" />

**Comment by fottbyte** [comment]
same
